const posts = [
  // ==== TECH ====
  {
    id: 1,
    title: "React Basics for Beginners",
    image: "https://plus.unsplash.com/premium_photo-1720287601920-ee8c503af775?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OXx8Y29kaW5nfGVufDB8fDB8fHww",
    description: "Learn the building blocks of React including JSX and components.",
    date: "2025-07-30",
    category: "Tech",
  },
  {
    id: 2,
    title: "Using Git and GitHub Effectively",
    image: "https://cdn-icons-png.flaticon.com/512/25/25231.png",
    description: "Version control and collaboration made easy.",
    date: "2025-07-25",
    category: "Tech",
  },
  {
    id: 3,
    title: "Intro to JavaScript ES6",
    image: "https://www.shutterstock.com/image-illustration/javascript-es6-vector-logo-disign-260nw-2438402733.jpg",
    description: "Arrow functions, let/const, spread operators and more.",
    date: "2025-07-20",
    category: "Tech",
  },
  {
    id: 4,
    title: "Building Responsive UIs",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQMa5plqZrmmxeU48xWzI4le2ZOsddIJCHZuQ&s",
    description: "Learn about Flexbox and CSS Grid.",
    date: "2025-07-18",
    category: "Tech",
  },
  {
    id: 5,
    title: "Exploring TypeScript",
    image: "https://cdn3d.iconscout.com/3d/free/preview/free-typescript-9294849-7577992.png?f=webp&h=700",
    description: "Why and how to use TypeScript with React.",
    date: "2025-07-15",
    category: "Tech",
  },
  {
    id: 6,
    title: "Next.js vs Create React App",
    image: "https://refine-web.imgix.net/blog/2023-10-10-nextjs-vs-react/social-2.png?w=1788",
    description: "What should you use for your next project?",
    date: "2025-07-12",
    category: "Tech",
  },
  {
    id: 7,
    title: "Tailwind CSS in React",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRCfdHfqPZXbLb88OeoXYQfcfoJlI5u76RVvA&s",
    description: "Utility-first CSS framework in React.",
    date: "2025-07-10",
    category: "Tech",
  },
  {
    id: 8,
    title: "Optimizing React Performance",
    image: "https://www.simform.com/wp-content/uploads/2019/04/react_app_performance.jpg",
    description: "UseMemo, UseCallback, Lazy Loading and more.",
    date: "2025-07-05",
    category: "Tech",
  },

  // ==== TRAVEL ====
  {
    id: 9,
    title: "A Journey Through Hunza Valley",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0eBlveN6voBU7AaExaAop0jdh2TkXl5AOvg&s",
    description: "Experience the beauty of northern Pakistan.",
    date: "2025-07-30",
    category: "Travel",
  },
  {
    id: 10,
    title: "Backpacking Across Europe",
    image: "https://images.travelandleisureasia.com/wp-content/uploads/sites/2/2023/11/20122038/ljublianica.jpeg",
    description: "Budget-friendly travel tips and places to visit.",
    date: "2025-07-27",
    category: "Travel",
  },
  {
    id: 11,
    title: "Top 5 Beaches in Asia",
    image: "https://www.intrepidtravel.com/adventures/wp-content/uploads/2017/05/railay-beach.jpg",
    description: "White sands, turquoise waters, and peace.",
    date: "2025-07-25",
    category: "Travel",
  },
  {
    id: 12,
    title: "Islamabad: The World's Second Most Beautiful Capital",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Faisal_Mosque_and_Margalla_Hills.jpg/1200px-Faisal_Mosque_and_Margalla_Hills.jpg",
    description: "A peaceful city with green hills, modern spots, and scenic views.",
    date: "2025-07-22",
    category: "Travel",
  },
  {
    id: 13,
    title: "Exploring Lahore's Heritage",
    image: "https://www.vouch365.com/blog/wp-content/uploads/2024/01/jamshaid-mughal-ZuyCsUaRpb0-unsplash-scaled.jpg",
    description: "A walk through Mughal-era architecture.",
    date: "2025-07-20",
    category: "Travel",
  },
  {
    id: 14,
    title: "5-Day Itinerary for Skardu",
    image: "https://visitgilgitbaltistan.gov.pk/storage/images/EgzRNEiwXoQdYYriBJZ4pfaOqAZtEE-metaU2hhbmdyaWxhLF9Mb3dlcl9LYWNodXJhX0xha2UuanBn-.jpg",
    description: "Breathtaking views and peaceful valleys.",
    date: "2025-07-15",
    category: "Travel",
  },
  {
    id: 15,
    title: "Top Hiking Trails in Pakistan",
    image: "https://www.cda.gov.pk/Assets/destinations/Trail-5.png",
    description: "Best trails from north to south.",
    date: "2025-07-10",
    category: "Travel",
  },
  {
    id: 16,
    title: "Why I Loved Murree in Summer",
    image: "https://media-cdn.tripadvisor.com/media/attractions-splice-spp-674x446/07/38/e9/42.jpg",
    description: "Cool breeze and crowded bazaars.",
    date: "2025-07-05",
    category: "Travel",
  },

  // ==== FOOD ====
  {
    id: 17,
    title: "Easy Homemade Biryani",
    image: "https://ministryofcurry.com/wp-content/uploads/2024/06/chicken-biryani-5.jpg",
    description: "Spicy, flavorful and simple to make.",
    date: "2025-07-30",
    category: "Food",
  },
  {
    id: 18,
    title: "My Favorite Desserts",
    image: "https://thekitchencommunity.org/wp-content/uploads/2021/10/choc-shutterstock_394680466.jpg",
    description: "Chocolate, cakes, and everything sweet.",
    date: "2025-07-27",
    category: "Food",
  },
  {
    id: 19,
    title: "Pakistani Street Food Tour",
    image: "https://foodaazz.com/wp-content/uploads/2024/07/Add-a-heading.png",
    description: "Gol gappay, bun kabab, and more!",
    date: "2025-07-25",
    category: "Food",
  },
  {
    id: 20,
    title: "Chill Treats: Best Ice Cream in Town",
    image: "https://cdn.britannica.com/50/80550-050-5D392AC7/Scoops-kinds-ice-cream.jpg",
    description: "From classic vanilla to exotic flavors, explore the coolest ice cream spots around.",
    date: "2025-07-23",
    category: "Food",
  },
  {
    id: 21,
    title: "Sweet Tooth Favorites",
    image: "https://teddyland.pk/wp-content/uploads/2024/05/Pakistani-Mithai-An-Irreplaceable-Delicacy.jpg",
    description: "Discover the must-try traditional and modern sweets that everyone loves.",
    date: "2025-07-20",
    category: "Food",
  },
  {
    id: 22,
    title: "Desi Breakfast Delights",
    image: "https://images.deliveryhero.io/image/fd-pk/LH/jaw2-listing.jpg",
    description: "From halwa puri to anda paratha — the best ways to start your morning.",
    date: "2025-07-18",
    category: "Food",
  },
  {
    id: 23,
    title: "Rainy Day Favorites",
    image: "https://media.istockphoto.com/id/498271642/photo/busy-street-food-vendor-selling-indian-pakoras-samosasa-and-snacks.jpg?s=612x612&w=0&k=20&c=Af4_NlWDpw_aWNKc2ZfJ5ygbfKy8YaIQmL7m7MYu4E0=",
    description: "Hot pakoras and crispy samosas — the perfect pair to enjoy with a cup of chai when it’s pouring outside.",
    date: "2025-07-15",
    category: "Food",
  },
  {
    id: 24,
    title: "My Daily Brew",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtap7fZuPgO55dLTjGfwKDQuY1L6QDxJCV9B_yEF6wHNiimbJflC-DOHoQRc4QK-ScB0M&usqp=CAU",
    description: "From creamy lattes to strong espresso — perfect sips for every mood and moment.",
    date: "2025-07-10",
    category: "Food",
  },
];

export default posts;
